#pragma once
#ifndef __CONSOLE_COLOR_H
#define __CONSOLE_COLOR_H
#include <Windows.h>
enum class ConsoleFGColor
{
    Red = FOREGROUND_INTENSITY | FOREGROUND_RED,
    Green = FOREGROUND_INTENSITY | FOREGROUND_GREEN,
    Blue = FOREGROUND_INTENSITY | FOREGROUND_BLUE,
    Yellow = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN,
    Purple = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_BLUE,
    Cyan = FOREGROUND_INTENSITY | FOREGROUND_GREEN | FOREGROUND_BLUE,
    Gray = FOREGROUND_INTENSITY,
    White = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,
    HighWhite = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,
    Black = 0,
};
enum class ConsoleBGColor
{
    Red = BACKGROUND_INTENSITY | BACKGROUND_RED,
    Green = BACKGROUND_INTENSITY | BACKGROUND_GREEN,
    Blue = BACKGROUND_INTENSITY | BACKGROUND_BLUE,
    Yellow = BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_GREEN,
    Purple = BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_BLUE,
    Cyan = BACKGROUND_INTENSITY | BACKGROUND_GREEN | BACKGROUND_BLUE,
    White = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE,
    HighWhite = BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE,
    Black = 0,
};
#endif // !__CONSOLE_COLOR_H